services:
  backend:
    build: ./backend
    container_name: tts-backend
    user: "0:0"
    environment:
      - NODE_ENV=production
      - PORT=8080
      # Set this to your public domain if you plan to access backend directly from other origins
      - ALLOW_ORIGINS=${ALLOW_ORIGINS}
    volumes:
      - backend-data:/app/backend/data
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: tts-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/certbot-webroot:/var/www/certbot:ro
    restart: unless-stopped

networks:
  default:
    name: tiktokshop_net

volumes:
  backend-data: