version: '3.8'

services:
  frontend:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.https.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/certbot-webroot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes: {}
